### ISSUE TITLE
Merge JournalVolume nodes with Journal nodes

### ISSUE THREAD

**Issue by qianzhu2018** [ncats/alert#21]
Currently there is one class named JournalVolume and one Journal class, it doesn't make sense we have these two separate classes, can we merge JournalVolume to Journal?

**Comment by brandon-gong** [comment]
It appears that `Journal` are groups of `JournalVolume`s with shared ESSN/ISSN/medlineAbbreviation/nlmid/title. Is this not a useful way to group articles together in a hierarchical manner?

If we do merge `JournalVolume` to `Journal`, should we then copy the attributes from `Journal` into each connected `JournalVolume` so we don't lose this information? i.e. new `Journal` nodes would have `essn`, `issn`, `medlineAbbreviation`, `nlmid`, `title`, `dateOfPublication`, `issue`, `journalIssueId`, `monthOfPublication`, `printPublicationDate`, `volume`, and `yearOfPublication` properties?

**Comment by qianzhu2018** [comment]
Leave it there for now, might be come back later
