### ISSUE TITLE
Duplicate Pubtator Annotations

### ISSUE THREAD

**Issue by wzkariampuzha** [ncats/alert#3]
Right now Pubtator annotates the title and the abstract and returns annotations with duplicate `infos_identifier` numbers. These need to be removed and new annotations need to be able to added only if they are have not already been added to that article. 

Constraints
- Cannot lowercase the text before sending it to Pubtator due to case differences in the gene space. 
- Instead of Title and Abstract, we are allowed to concatenate title+abstract, however, it would be better if these were still kept separate.
- This needs to be written in the weekly update function
- Existing duplicate Pubtator annotations need to be removed.

**Comment by brandon-gong** [comment]
- Assuming two nodes are duplicates iff they have the exact same (case sensitive) `infons_identifier`, `infons_type`, and `text`.
- Remove `type` from `PubtatorAnnotation` nodes

**Comment by brandon-gong** [comment]
https://gist.github.com/brandon-gong/a08d0fd7ab4e0a116e46fa6506cfb2aa

**Comment by qianzhu2018** [comment]
almost done
