### ISSUE TITLE
Update neo4J regularly

### ISSUE THREAD

**Issue by wzkariampuzha** [ncats/alert#5]
query PubMed regularly and update neo4J db

**Comment by qianzhu2018** [comment]
We also need to query OMIM API regularly and check any newly added references

**Comment by wzkariampuzha** [comment]
Assigned to Devon

**Comment by wzkariampuzha** [comment]
Also remove publications older than 50 years.

**Comment by devonleadman** [comment]
Create a reoccurring python script that only retrieves PubMed articles and OMIM since last retrieval (runs after initial_loading file)
- create a txt or json file containing last date the script was ran and replace the minimum date with that date to the current date

**Comment by wzkariampuzha** [comment]
@devonleadman Fixed the update function here: https://github.com/ncats/alert/issues/9
