### ISSUE TITLE
Lose our PubMed API query restriction

### ISSUE THREAD

**Issue by qianzhu2018** [ncats/alert#8]
One review comment from the reviewer:
the authors limits to 1000 the amount of PMIDs without explanations. Limit imposed to 1K for all literature 1900-2021 creates the risk to lose important more novel findings. I would suggest to reduce temporal limit to last 50 years (1971-2021) and enhance limits to X (2000?) and see whether there is a gain in information.... Quality first!

**Comment by wzkariampuzha** [comment]
Assigned to Richard

**Comment by wzkariampuzha** [comment]
@devonleadman addressed the 50 year limit here https://github.com/ncats/alert/issues/9 - changed it to a 50 year sliding window

**Comment by qianzhu2018** [comment]
Richard has done this task

**Comment by wzkariampuzha** [comment]
@qianzhu2018 @12yye This issue needs to be linked to a pull request that is reviewed and accepted by someone else for it to be closed.
